  ALTER TABLE "RMREP"."ANNOTATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RMREP_TS"  ENABLE ;
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("ANNOTATION_TEXT" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION" MODIFY ("ORPHAN" NOT NULL ENABLE);