CREATE TABLE "RMREP"."ANNOTATION" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(19,0), 
	"ACTIVE" VARCHAR2(255 CHAR), 
	"ANNOTATION_TEXT" VARCHAR2(4000 CHAR), 
	"ANNOTATION_TYPE" VARCHAR2(255 CHAR), 
	"ATTACHMENT_NAME" VARCHAR2(255 CHAR), 
	"CATEGORY" VARCHAR2(255 CHAR), 
	"CELL_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(30 CHAR), 
	"CREATED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(30 CHAR), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"PAGE" VARCHAR2(50 CHAR), 
	"PAGE_PATH" VARCHAR2(255 CHAR), 
	"SECTION" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"TAB" VARCHAR2(50 CHAR), 
	"TAG_STRING" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(50 CHAR), 
	"XCOORD" VARCHAR2(50 CHAR), 
	"YCOORD" VARCHAR2(50 CHAR), 
	"ORPHAN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RMREP_TS" 