  CREATE TABLE "RMREP"."APPLICATION_CONSTANT" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(19,0), 
	"KEY" VARCHAR2(50 CHAR), 
	"VALUE" VARCHAR2(4000 CHAR),
	"ENCRYPTED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RMREP_TS" ;

Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (0,0,'admin','weblogic',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (1,0,'serverport','9502',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (2,0,'protocol','http',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (3,0,'uploadpath','/app/oracle',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (7,0,'security','n',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (4,0,'smtp_server','dummy',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (5,0,'smtp_sender','dummy',0);
Insert into RMREP.APPLICATION_CONSTANT (ID,VERSION,KEY,VALUE,ENCRYPTED) values (6,0,'smtp_password','dummy',0);
commit;
