  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" ADD PRIMARY KEY ("ANNOTATION_ID", "TARGET_PLATFORM", "SHARED_USER", "MOD_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RMREP_TS"  ENABLE;
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("TARGET_UNIQUE_ID" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("SHARE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("MOD_DATE" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("SHARED_USER" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("TARGET_PLATFORM" NOT NULL ENABLE);
  ALTER TABLE "RMREP"."ANNOTATION_SHARE" MODIFY ("ANNOTATION_ID" NOT NULL ENABLE);