  CREATE TABLE "RMREP"."ANNOTATION_SHARE" 
   (	"ANNOTATION_ID" NUMBER(10,0), 
	"TARGET_PLATFORM" VARCHAR2(15 CHAR), 
	"SHARED_USER" VARCHAR2(20 CHAR), 
	"MOD_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"SHARE_TEXT" VARCHAR2(4000 CHAR), 
	"TARGET_UNIQUE_ID" VARCHAR2(50 CHAR), 
	"ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RMREP_TS" 